# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-08-27 11:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InterFace',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discription', models.TextField(null=True, verbose_name='\u63a5\u53e3\u63cf\u8ff0')),
                ('theurl', models.CharField(max_length=500, verbose_name='\u63a5\u53e3url')),
                ('proxy', models.CharField(max_length=20, null=True, verbose_name='\u4ee3\u7406\u5730\u5740')),
                ('postdata', models.CharField(max_length=200, null=True, verbose_name='post\u53c2\u6570')),
                ('expection', models.CharField(max_length=200, verbose_name='\u9884\u671f\u54cd\u5e94')),
                ('created_time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Method',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10, verbose_name='\u8bf7\u6c42\u65b9\u6cd5')),
            ],
        ),
        migrations.CreateModel(
            name='Station',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10, verbose_name='\u5b9e\u9645\u72b6\u6001')),
            ],
        ),
        migrations.AddField(
            model_name='interface',
            name='method',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='interfacescanner.Method', verbose_name='\u8bf7\u6c42\u65b9\u5f0f'),
        ),
        migrations.AddField(
            model_name='interface',
            name='station',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='interfacescanner.Station', verbose_name='\u5b9e\u9645\u72b6\u6001'),
        ),
    ]
