# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-09-02 04:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interfacescanner', '0003_auto_20170902_1227'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interface',
            name='proxy',
            field=models.GenericIPAddressField(verbose_name='\u4ee3\u7406\u5730\u5740'),
        ),
        migrations.AlterField(
            model_name='interface',
            name='station',
            field=models.BooleanField(default=False, verbose_name='\u662f\u5426\u6709\u6548'),
        ),
        migrations.AlterField(
            model_name='interface',
            name='theurl',
            field=models.URLField(max_length=500, verbose_name='\u63a5\u53e3url'),
        ),
        migrations.DeleteModel(
            name='Station',
        ),
    ]
