# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-10-15 15:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interfacescanner', '0005_auto_20170902_1316'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interface',
            name='name',
            field=models.CharField(default='', max_length=100, verbose_name='\u63a5\u53e3\u63cf\u8ff0'),
        ),
    ]
