# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-10-15 16:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interfacescanner', '0006_auto_20171015_2345'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interface',
            name='name',
            field=models.CharField(max_length=100, verbose_name='\u63a5\u53e3\u63cf\u8ff0'),
        ),
    ]
